/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import modelBeans.ModalityModel;
import modelBeans.MonthlyModel;
import modelConnection.ConnectionDB;
import modelBeans.PersonModel;
import modelBeans.StudentModel;
import modelDao.ModalityDao;
import modelDao.MonthlyDao;
import modelDao.PersonDao;
import modelDao.StudentDao;

/**
 *
 * @author kaleo
 */
public class FormRegisterStudent extends javax.swing.JFrame {

    ConnectionDB cntn = new ConnectionDB();
    PersonModel personMod = new PersonModel();
    StudentModel studentMod = new StudentModel();
    MonthlyModel monthlyMod = new MonthlyModel();
    ModalityModel modalityMod = new ModalityModel();
    PersonDao personCon = new PersonDao();
    StudentDao studentCon = new StudentDao();
    MonthlyDao monthlyDao = new MonthlyDao();
    ModalityDao modalityDao = new ModalityDao();
    Date data = new Date (System.currentTimeMillis());
    SimpleDateFormat dateFormat =  new SimpleDateFormat("ddMMyyyy");
    private int flagButton = 0;
    private int flagButton2 = 0;
    
    public FormRegisterStudent() {
        initComponents();
        setLocationRelativeTo(null);//centralizar tela
        disableText();
        btnSave.setEnabled(false);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
        setComboBox();
        txtDateRegistration.setText(dateFormat.format(data));
        txtValid.setText(dateFormat.format(data));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdPnlStudent = new javax.swing.JTabbedPane();
        pnlFormStudent = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        lblTelephone = new javax.swing.JLabel();
        cbxSex = new javax.swing.JComboBox();
        lblSituation = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        cbxSituation = new javax.swing.JComboBox();
        txtCpf = new javax.swing.JFormattedTextField();
        txtPhone = new javax.swing.JFormattedTextField();
        lblStreet = new javax.swing.JLabel();
        lblDistrict = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblComplement = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtDistrict = new javax.swing.JTextField();
        txtComplement = new javax.swing.JTextField();
        txtCep = new javax.swing.JFormattedTextField();
        cbxState = new javax.swing.JComboBox<>();
        txtCity = new javax.swing.JTextField();
        pnlStudentRegistration = new javax.swing.JPanel();
        lblModality = new javax.swing.JLabel();
        cbxModality = new javax.swing.JComboBox();
        lblModality2 = new javax.swing.JLabel();
        cbxModality2 = new javax.swing.JComboBox();
        lblPlan = new javax.swing.JLabel();
        cbxPlan = new javax.swing.JComboBox();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JFormattedTextField();
        lblValid = new javax.swing.JLabel();
        txtValid = new javax.swing.JFormattedTextField();
        pnlButtonsRegistration = new javax.swing.JPanel();
        btnSaveRegistration = new javax.swing.JButton();
        btnUpdateRegistration = new javax.swing.JButton();
        btnCancelRegistration = new javax.swing.JButton();
        lblRegistration = new javax.swing.JLabel();
        txtDateRegistration = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Academia King Muay Thai");
        getContentPane().setLayout(null);

        tbdPnlStudent.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tbdPnlStudent.setPreferredSize(new java.awt.Dimension(800, 600));

        pnlFormStudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlFormStudent.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlFormStudent.setPreferredSize(new java.awt.Dimension(700, 500));
        pnlFormStudent.setLayout(null);

        lblName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblName.setText("Nome:");
        pnlFormStudent.add(lblName);
        lblName.setBounds(10, 50, 60, 30);

        lblSex.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSex.setText("Sexo:");
        pnlFormStudent.add(lblSex);
        lblSex.setBounds(470, 50, 50, 30);

        lblEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEmail.setText("E-mail:");
        pnlFormStudent.add(lblEmail);
        lblEmail.setBounds(10, 90, 60, 30);

        txtName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pnlFormStudent.add(txtName);
        txtName.setBounds(70, 50, 390, 30);

        txtEmail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pnlFormStudent.add(txtEmail);
        txtEmail.setBounds(70, 90, 390, 30);

        lblCpf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCpf.setText("CPF:");
        pnlFormStudent.add(lblCpf);
        lblCpf.setBounds(10, 10, 60, 30);

        lblTelephone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTelephone.setText("Telefone:");
        pnlFormStudent.add(lblTelephone);
        lblTelephone.setBounds(310, 10, 100, 30);

        cbxSex.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbxSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", "Outro" }));
        cbxSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSexActionPerformed(evt);
            }
        });
        pnlFormStudent.add(cbxSex);
        cbxSex.setBounds(520, 50, 140, 30);

        lblSituation.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSituation.setText("Situação:");
        pnlFormStudent.add(lblSituation);
        lblSituation.setBounds(470, 90, 80, 30);

        pnlButtons.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Adicionar usuário masculino-104.png"))); // NOI18N
        btnCreate.setToolTipText("Adicionar novo Aluno");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCreate);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Salvar Filled-50.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSave);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Editar-104.png"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlButtons.add(btnUpdate);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Cancelar-104.png"))); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCancel);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Lixo-104.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlButtons.add(btnDelete);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Pesquisa propriedade-50.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSearch);

        pnlFormStudent.add(pnlButtons);
        pnlButtons.setBounds(670, 10, 100, 480);

        cbxSituation.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbxSituation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo", "Bloqueado" }));
        pnlFormStudent.add(cbxSituation);
        cbxSituation.setBounds(550, 90, 110, 30);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCpf.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCpf.setMinimumSize(new java.awt.Dimension(5, 16));
        pnlFormStudent.add(txtCpf);
        txtCpf.setBounds(70, 10, 220, 30);

        try {
            txtPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhone.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pnlFormStudent.add(txtPhone);
        txtPhone.setBounds(390, 10, 270, 30);

        lblStreet.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblStreet.setText("Rua:");
        pnlFormStudent.add(lblStreet);
        lblStreet.setBounds(10, 130, 60, 30);

        lblDistrict.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDistrict.setText("Bairro:");
        pnlFormStudent.add(lblDistrict);
        lblDistrict.setBounds(10, 170, 53, 30);

        lblNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNumber.setText("Nro:");
        pnlFormStudent.add(lblNumber);
        lblNumber.setBounds(470, 130, 34, 30);

        lblCep.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCep.setText("Cep:");
        pnlFormStudent.add(lblCep);
        lblCep.setBounds(10, 210, 38, 30);

        lblState.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblState.setText("Estado:");
        pnlFormStudent.add(lblState);
        lblState.setBounds(150, 210, 70, 30);

        lblCity.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCity.setText("Cidade:");
        pnlFormStudent.add(lblCity);
        lblCity.setBounds(380, 210, 70, 30);

        lblComplement.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblComplement.setText("Complemento:");
        pnlFormStudent.add(lblComplement);
        lblComplement.setBounds(380, 170, 120, 30);

        txtStreet.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pnlFormStudent.add(txtStreet);
        txtStreet.setBounds(70, 130, 390, 31);

        txtNumber.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pnlFormStudent.add(txtNumber);
        txtNumber.setBounds(510, 130, 150, 31);

        txtDistrict.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pnlFormStudent.add(txtDistrict);
        txtDistrict.setBounds(70, 170, 300, 31);

        txtComplement.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pnlFormStudent.add(txtComplement);
        txtComplement.setBounds(500, 170, 160, 31);

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pnlFormStudent.add(txtCep);
        txtCep.setBounds(50, 210, 90, 31);

        cbxState.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbxState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "RJ" }));
        pnlFormStudent.add(cbxState);
        cbxState.setBounds(220, 210, 150, 31);

        txtCity.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pnlFormStudent.add(txtCity);
        txtCity.setBounds(450, 210, 210, 31);

        tbdPnlStudent.addTab("Cadastro do Aluno", pnlFormStudent);

        lblModality.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblModality.setText("Modalidade 1:");

        cbxModality.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbxModality.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxModalityItemStateChanged(evt);
            }
        });
        cbxModality.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxModalityMouseClicked(evt);
            }
        });
        cbxModality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxModalityActionPerformed(evt);
            }
        });

        lblModality2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblModality2.setText("Modalidade 2:");

        cbxModality2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbxModality2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxModality2ActionPerformed(evt);
            }
        });

        lblPlan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPlan.setText("Tipo Plano:");

        cbxPlan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbxPlan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mensal", "Trimestral\t", "Semestral\t", "Anual" }));
        cbxPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPlanActionPerformed(evt);
            }
        });

        lblPrice.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPrice.setText("Valor:");

        try {
            txtPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.00")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPrice.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        lblValid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblValid.setText("Vencimento:");

        try {
            txtValid.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtValid.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        pnlButtonsRegistration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSaveRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Salvar Filled-50.png"))); // NOI18N
        btnSaveRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRegistrationActionPerformed(evt);
            }
        });
        pnlButtonsRegistration.add(btnSaveRegistration);

        btnUpdateRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Editar-104.png"))); // NOI18N
        btnUpdateRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRegistrationActionPerformed(evt);
            }
        });
        pnlButtonsRegistration.add(btnUpdateRegistration);

        btnCancelRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Cancelar-104.png"))); // NOI18N
        btnCancelRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRegistrationActionPerformed(evt);
            }
        });
        pnlButtonsRegistration.add(btnCancelRegistration);

        lblRegistration.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblRegistration.setText("Matricula:");

        try {
            txtDateRegistration.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDateRegistration.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlStudentRegistrationLayout = new javax.swing.GroupLayout(pnlStudentRegistration);
        pnlStudentRegistration.setLayout(pnlStudentRegistrationLayout);
        pnlStudentRegistrationLayout.setHorizontalGroup(
            pnlStudentRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentRegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStudentRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValid, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModality, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModality2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnlStudentRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPrice)
                    .addComponent(txtValid)
                    .addComponent(cbxPlan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDateRegistration)
                    .addComponent(cbxModality, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxModality2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(pnlButtonsRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pnlStudentRegistrationLayout.setVerticalGroup(
            pnlStudentRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentRegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStudentRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStudentRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModality, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxModality, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStudentRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModality2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxModality2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStudentRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStudentRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStudentRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(340, Short.MAX_VALUE))
            .addGroup(pnlStudentRegistrationLayout.createSequentialGroup()
                .addComponent(pnlButtonsRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 78, Short.MAX_VALUE))
        );

        tbdPnlStudent.addTab("Matricula", pnlStudentRegistration);

        getContentPane().add(tbdPnlStudent);
        tbdPnlStudent.setBounds(0, 0, 800, 600);

        setBounds(0, 0, 810, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSexActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (flagButton==1){
            personMod.setCpf(txtCpf.getText().replace(".","").replace("-",""));
            //personMod.setPhone(txtPhone.getText());
            personMod.setName(txtName.getText());
            personMod.setSex((String)cbxSex.getSelectedItem());
            //personMod.setEmail(txtEmail.getText());
            personMod.setStreet(txtStreet.getText());
            personMod.setDistrict(txtDistrict.getText());
            personMod.setNum(Integer.parseInt(txtNumber.getText()));
            personMod.setCep(txtCep.getText().replace("-",""));
            personMod.setCity(txtCity.getText());
            personMod.setState((String)cbxState.getSelectedItem());
            personMod.setComplement(txtComplement.getText());
            studentMod.setSituation((String)cbxSituation.getSelectedItem());
            studentCon.saveStudent(personMod, studentMod);
            clearText();
            btnCancel.setEnabled(true);
            btnDelete.setEnabled(true);
            btnUpdate.setEnabled(true);
        }
        else {
            personMod.setCpf(txtCpf.getText().replace(".","").replace("-",""));
            //personMod.setPhone(txtPhone.getText());
            personMod.setName(txtName.getText());
            personMod.setSex((String)cbxSex.getSelectedItem());
            //personMod.setEmail(txtEmail.getText());
            personMod.setStreet(txtStreet.getText());
            personMod.setDistrict(txtDistrict.getText());
            personMod.setNum(Integer.parseInt(txtNumber.getText()));
            personMod.setCep(txtCep.getText().replace("-",""));
            personMod.setCity(txtCity.getText());
            personMod.setState((String)cbxState.getSelectedItem());
            personMod.setComplement(txtComplement.getText());
            studentMod.setCpf(txtCpf.getText().replace(".","").replace("-",""));
            studentMod.setSituation((String)cbxSituation.getSelectedItem());
            personCon.updatePerson(personMod);
            studentCon.updateStudent(studentMod);
            disableText();
            btnCreate.setEnabled(false);
            btnSave.setEnabled(false);
            btnCancel.setEnabled(true);
            btnDelete.setEnabled(true);
            btnUpdate.setEnabled(true);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
            personMod.setSearch(txtCpf.getText());
            studentMod.setSearch(txtCpf.getText());
            PersonModel model = personCon.searchPerson(personMod);
            StudentModel stmodel = studentCon.searchStudent(studentMod);
            txtCpf.setText(model.getCpf());
            //personMod.setPhone(txtPhone.getText());
            txtName.setText(model.getName());
            cbxSex.setSelectedItem(model.getSex());
            //personMod.setEmail(txtEmail.getText());
            txtStreet.setText(model.getStreet());
            txtDistrict.setText(model.getDistrict());
            txtNumber.setText(Integer.toString(model.getNum()));
            txtCep.setText(model.getCep());
            txtCity.setText(model.getCity());
            cbxState.setSelectedItem(model.getState());
            txtComplement.setText(model.getComplement());
            cbxSituation.setSelectedItem(stmodel.getSituation());
            btnDelete.setEnabled(true);
            btnUpdate.setEnabled(true);
            btnCreate.setEnabled(false);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
            flagButton=1;
            enabledText();
            btnSave.setEnabled(true);
            btnCancel.setEnabled(true);
            btnSearch.setEnabled(false);
            btnDelete.setEnabled(false);
            btnUpdate.setEnabled(false);        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearText();
        disableText();
        btnCreate.setEnabled(true);
        btnDelete.setEnabled(false);
        btnSearch.setEnabled(true);  
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        flagButton = 2;
        enabledText();
        btnSave.setEnabled(true);
        btnDelete.setEnabled(false);
        btnSearch.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int question = 0;
        question = JOptionPane.showConfirmDialog(rootPane, "Deseja relamente excluir os dados ?");
        if (question==JOptionPane.YES_OPTION){
            personMod.setCpf(txtCpf.getText().replace(".","").replace("-",""));
            studentCon.deleteStudent(personMod, studentMod);
            clearText();
            disableText();
            btnDelete.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void setComboBox (){
        MonthlyDao monthlyDao = new MonthlyDao();
        cbxModality.removeAllItems();
        cbxModality2.removeAllItems();//remove os itens atuais do comboBox.
        ArrayList produtos = monthlyDao.findAll(); //'produtoDAO' é meu objeto que retorna os produtos do banco.
        Iterator i = produtos.iterator();
        Iterator j = produtos.iterator();
        while(i.hasNext()) {
            cbxModality.addItem(String.valueOf(i.next()));
        }
        while(j.hasNext()) {
            cbxModality2.addItem(String.valueOf(j.next()));
        }
    }
    
    private void cbxModalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxModalityActionPerformed
        
    }//GEN-LAST:event_cbxModalityActionPerformed

    private void cbxModality2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxModality2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxModality2ActionPerformed

    private void cbxPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPlanActionPerformed

    private void btnSaveRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRegistrationActionPerformed
        if (flagButton2==1){
            monthlyMod.setDateRegistration(txtDateRegistration.getText());
            monthlyMod.setPlan((String)cbxPlan.getSelectedItem());
            monthlyMod.setPrice(Double.parseDouble(txtPrice.getText()));
            //personMod.setEmail(txtEmail.getText());
            personMod.setStreet(txtStreet.getText());
            personMod.setDistrict(txtDistrict.getText());
            personMod.setNum(Integer.parseInt(txtNumber.getText()));
            personMod.setCep(txtCep.getText().replace("-",""));
            personMod.setCity(txtCity.getText());
            personMod.setState((String)cbxState.getSelectedItem());
            personMod.setComplement(txtComplement.getText());
            studentMod.setSituation((String)cbxSituation.getSelectedItem());
            studentCon.saveStudent(personMod, studentMod);
            clearText();
            btnCancel.setEnabled(true);
            btnDelete.setEnabled(true);
            btnUpdate.setEnabled(true);
        }
        else {
            personMod.setCpf(txtCpf.getText().replace(".","").replace("-",""));
            //personMod.setPhone(txtPhone.getText());
            personMod.setName(txtName.getText());
            personMod.setSex((String)cbxSex.getSelectedItem());
            //personMod.setEmail(txtEmail.getText());
            personMod.setStreet(txtStreet.getText());
            personMod.setDistrict(txtDistrict.getText());
            personMod.setNum(Integer.parseInt(txtNumber.getText()));
            personMod.setCep(txtCep.getText().replace("-",""));
            personMod.setCity(txtCity.getText());
            personMod.setState((String)cbxState.getSelectedItem());
            personMod.setComplement(txtComplement.getText());
            studentMod.setCpf(txtCpf.getText().replace(".","").replace("-",""));
            studentMod.setSituation((String)cbxSituation.getSelectedItem());
            personCon.updatePerson(personMod);
            studentCon.updateStudent(studentMod);
            disableText();
            btnCreate.setEnabled(false);
            btnSave.setEnabled(false);
            btnCancel.setEnabled(true);
            btnDelete.setEnabled(true);
            btnUpdate.setEnabled(true);
        }
    }//GEN-LAST:event_btnSaveRegistrationActionPerformed

    private void btnUpdateRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRegistrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateRegistrationActionPerformed

    private void btnCancelRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRegistrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelRegistrationActionPerformed

    private void cbxModalityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxModalityMouseClicked
        
    }//GEN-LAST:event_cbxModalityMouseClicked

    private void cbxModalityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxModalityItemStateChanged
        modalityMod.setSearch((String)cbxModality.getSelectedItem());
        modalityDao.searchModality(modalityMod);
        txtPrice.setText(Double.toString(modalityMod.getPrice()));
    }//GEN-LAST:event_cbxModalityItemStateChanged
    
    private void clearText (){
        txtCpf.setText("");
        txtName.setText("");
        //cbxSex.set("");
        txtEmail.setText("");
        //cbxSituation.set("");
        txtStreet.setText("");
        txtDistrict.setText("");
        txtComplement.setText("");
        txtNumber.setText("");
        txtCep.setText("");
        txtCity.setText("");
        //cbxState.setText("");
    }
    
    private void enabledText (){
        txtCpf.setEnabled(true);
        txtPhone.setEnabled(true);
        txtName.setEnabled(true);
        cbxSex.setEnabled(true);
        txtEmail.setEnabled(true);
        cbxSituation.setEnabled(true);
        txtStreet.setEnabled(true);
        txtDistrict.setEnabled(true);
        txtComplement.setEnabled(true);
        txtNumber.setEnabled(true);
        txtCep.setEnabled(true);
        txtCity.setEnabled(true);
        cbxState.setEnabled(true);
    }
    
    private void disableText (){
        txtCpf.setEnabled(true);
        txtPhone.setEnabled(false);
        txtName.setEnabled(false);
        cbxSex.setEnabled(false);
        txtEmail.setEnabled(false);
        cbxSituation.setEnabled(false);
        txtStreet.setEnabled(false);
        txtDistrict.setEnabled(false);
        txtComplement.setEnabled(false);
        txtNumber.setEnabled(false);
        txtCep.setEnabled(false);
        txtCity.setEnabled(false);
        cbxState.setEnabled(false);
        btnSave.setEnabled(false);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegisterStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelRegistration;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveRegistration;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateRegistration;
    private javax.swing.JComboBox cbxModality;
    private javax.swing.JComboBox cbxModality2;
    private javax.swing.JComboBox cbxPlan;
    private javax.swing.JComboBox cbxSex;
    private javax.swing.JComboBox cbxSituation;
    private javax.swing.JComboBox<String> cbxState;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblComplement;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDistrict;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblModality;
    private javax.swing.JLabel lblModality2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPlan;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblSituation;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblValid;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlButtonsRegistration;
    private javax.swing.JPanel pnlFormStudent;
    private javax.swing.JPanel pnlStudentRegistration;
    private javax.swing.JTabbedPane tbdPnlStudent;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtComplement;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDateRegistration;
    private javax.swing.JTextField txtDistrict;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JFormattedTextField txtPhone;
    private javax.swing.JFormattedTextField txtPrice;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JFormattedTextField txtValid;
    // End of variables declaration//GEN-END:variables
}
