/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import modelConnection.ConnectionDB;
import modelDao.PersonDao;
import modelBeans.PersonModel;

/**
 *
 * @author kaleo
 */
public class FormRegisterStudent extends javax.swing.JFrame {

    /**
     * Creates new form FormRegisterStudent
     */
    
    PersonModel personMod = new PersonModel();
    ConnectionDB cntn = new ConnectionDB();
    PersonDao personCon = new PersonDao();
    private int flagButton = 0;
    //private boolean hasBeenClickedSearch = false;
    
    public FormRegisterStudent() {
        initComponents();
        setLocationRelativeTo(null);//centralizar tela
        disableText();
        btnSave.setEnabled(false);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        lblTelephone = new javax.swing.JLabel();
        cbxSex = new javax.swing.JComboBox();
        lblSituation = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        cbxSituation = new javax.swing.JComboBox();
        txtCpf = new javax.swing.JFormattedTextField();
        txtPhone = new javax.swing.JFormattedTextField();
        lblStreet = new javax.swing.JLabel();
        lblDistrict = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblComplement = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtDistrict = new javax.swing.JTextField();
        txtComplement = new javax.swing.JTextField();
        txtCep = new javax.swing.JFormattedTextField();
        cbxState = new javax.swing.JComboBox<>();
        txtCity = new javax.swing.JTextField();
        lblRegisterStudents = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Academia King Muay Thai");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(null);

        lblName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblName.setText("Nome:");
        jPanel1.add(lblName);
        lblName.setBounds(10, 60, 60, 30);

        lblSex.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSex.setText("Sexo:");
        jPanel1.add(lblSex);
        lblSex.setBounds(470, 60, 50, 30);

        lblEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEmail.setText("E-mail:");
        jPanel1.add(lblEmail);
        lblEmail.setBounds(10, 100, 60, 30);

        txtName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(txtName);
        txtName.setBounds(70, 60, 390, 30);

        txtEmail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(txtEmail);
        txtEmail.setBounds(70, 100, 390, 30);

        lblCpf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCpf.setText("CPF:");
        jPanel1.add(lblCpf);
        lblCpf.setBounds(10, 20, 60, 30);

        lblTelephone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTelephone.setText("Telefone:");
        jPanel1.add(lblTelephone);
        lblTelephone.setBounds(310, 20, 100, 30);

        cbxSex.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbxSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", "Outro" }));
        cbxSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSexActionPerformed(evt);
            }
        });
        jPanel1.add(cbxSex);
        cbxSex.setBounds(520, 60, 140, 30);

        lblSituation.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSituation.setText("Situação:");
        jPanel1.add(lblSituation);
        lblSituation.setBounds(470, 100, 80, 30);

        pnlButtons.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Adicionar usuário masculino-104.png"))); // NOI18N
        btnCreate.setToolTipText("Adicionar novo Aluno");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCreate);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Salvar Filled-50.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSave);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Editar-104.png"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlButtons.add(btnUpdate);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Cancelar-104.png"))); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCancel);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Lixo-104.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlButtons.add(btnDelete);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Pesquisa propriedade-50.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSearch);

        jPanel1.add(pnlButtons);
        pnlButtons.setBounds(670, 10, 100, 480);

        cbxSituation.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbxSituation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo", "Bloqueado" }));
        jPanel1.add(cbxSituation);
        cbxSituation.setBounds(550, 100, 110, 30);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCpf.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCpf.setMinimumSize(new java.awt.Dimension(5, 16));
        jPanel1.add(txtCpf);
        txtCpf.setBounds(70, 20, 220, 30);

        try {
            txtPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhone.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(txtPhone);
        txtPhone.setBounds(390, 20, 270, 30);

        lblStreet.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblStreet.setText("Rua:");
        jPanel1.add(lblStreet);
        lblStreet.setBounds(10, 140, 60, 30);

        lblDistrict.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDistrict.setText("Bairro:");
        jPanel1.add(lblDistrict);
        lblDistrict.setBounds(10, 180, 53, 30);

        lblNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNumber.setText("Nro:");
        jPanel1.add(lblNumber);
        lblNumber.setBounds(470, 140, 34, 30);

        lblCep.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCep.setText("Cep:");
        jPanel1.add(lblCep);
        lblCep.setBounds(10, 220, 38, 30);

        lblState.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblState.setText("Estado:");
        jPanel1.add(lblState);
        lblState.setBounds(150, 220, 70, 30);

        lblCity.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCity.setText("Cidade:");
        jPanel1.add(lblCity);
        lblCity.setBounds(380, 220, 70, 30);

        lblComplement.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblComplement.setText("Complemento:");
        jPanel1.add(lblComplement);
        lblComplement.setBounds(380, 180, 120, 30);

        txtStreet.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(txtStreet);
        txtStreet.setBounds(70, 140, 390, 31);

        txtNumber.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(txtNumber);
        txtNumber.setBounds(510, 140, 150, 31);

        txtDistrict.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(txtDistrict);
        txtDistrict.setBounds(70, 180, 300, 31);

        txtComplement.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(txtComplement);
        txtComplement.setBounds(500, 180, 160, 31);

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(txtCep);
        txtCep.setBounds(50, 220, 90, 31);

        cbxState.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbxState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "RJ" }));
        jPanel1.add(cbxState);
        cbxState.setBounds(220, 220, 150, 31);

        txtCity.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel1.add(txtCity);
        txtCity.setBounds(450, 220, 210, 31);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 30, 780, 550);

        lblRegisterStudents.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblRegisterStudents.setText("Cadastro de Alunos");
        getContentPane().add(lblRegisterStudents);
        lblRegisterStudents.setBounds(10, 10, 200, 22);

        setBounds(0, 0, 810, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSexActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (flagButton==1){
            personMod.setCpf(txtCpf.getText().replace(".","").replace("-",""));
            //personMod.setPhone(txtPhone.getText());
            personMod.setName(txtName.getText());
            personMod.setSex((String)cbxSex.getSelectedItem());
            //personMod.setEmail(txtEmail.getText());
            personMod.setStreet(txtStreet.getText());
            personMod.setDistrict(txtDistrict.getText());
            personMod.setNum(Integer.parseInt(txtNumber.getText()));
            personMod.setCep(txtCep.getText().replace("-",""));
            personMod.setCity(txtCity.getText());
            personMod.setState((String)cbxState.getSelectedItem());
            personCon.Save(personMod);
            clearText();
            btnCancel.setEnabled(true);
            btnDelete.setEnabled(true);
            btnUpdate.setEnabled(true);
        }
        else {
            personMod.setCpf(txtCpf.getText().replace(".","").replace("-",""));
            //personMod.setPhone(txtPhone.getText());
            personMod.setName(txtName.getText());
            personMod.setSex((String)cbxSex.getSelectedItem());
            //personMod.setEmail(txtEmail.getText());
            personMod.setStreet(txtStreet.getText());
            personMod.setDistrict(txtDistrict.getText());
            personMod.setNum(Integer.parseInt(txtNumber.getText()));
            personMod.setCep(txtCep.getText().replace("-",""));
            personMod.setCity(txtCity.getText());
            personMod.setState((String)cbxState.getSelectedItem());
            personCon.updatePerson(personMod);
            disableText();
            btnCreate.setEnabled(false);
            btnSave.setEnabled(false);
            btnCancel.setEnabled(true);
            btnDelete.setEnabled(true);
            btnUpdate.setEnabled(true);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
            personMod.setSearch(txtCpf.getText());
            PersonModel model = personCon.searchPerson(personMod);
            txtCpf.setText(model.getCpf());
            //personMod.setPhone(txtPhone.getText());
            txtName.setText(model.getName());
            cbxSex.setSelectedItem(model.getSex());
            //personMod.setEmail(txtEmail.getText());
            txtStreet.setText(model.getStreet());
            txtDistrict.setText(model.getDistrict());
            txtNumber.setText(Integer.toString(model.getNum()));
            txtCep.setText(model.getCep());
            txtCity.setText(model.getCity());
            cbxState.setSelectedItem(model.getState());
            btnDelete.setEnabled(true);
            btnUpdate.setEnabled(true);
            btnCreate.setEnabled(false);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
            flagButton=1;
            enabledText();
            btnSave.setEnabled(true);
            btnCancel.setEnabled(true);
            btnSearch.setEnabled(false);
            btnDelete.setEnabled(false);
            btnUpdate.setEnabled(false);        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearText();
        disableText();
        btnCreate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnSearch.setEnabled(true);
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        flagButton = 2;
        enabledText();
        btnSave.setEnabled(true);
        btnDelete.setEnabled(false);
        btnSearch.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int question = 0;
        question = JOptionPane.showConfirmDialog(rootPane, "Deseja relamente excluir os dados ?");
        if (question==JOptionPane.YES_OPTION){
            personMod.setCpf(txtCpf.getText().replace(".","").replace("-",""));
            personCon.deletePerson(personMod);
            clearText();
            disableText();
            btnDelete.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed
    
    private void clearText (){
        txtCpf.setText("");
        txtName.setText("");
        //cbxSex.set("");
        txtEmail.setText("");
        //cbxSituation.set("");
        txtStreet.setText("");
        txtDistrict.setText("");
        txtComplement.setText("");
        txtNumber.setText("");
        txtCep.setText("");
        txtCity.setText("");
        //cbxState.setText("");
    }
    
    private void enabledText (){
        txtCpf.setEnabled(true);
        txtPhone.setEnabled(true);
        txtName.setEnabled(true);
        cbxSex.setEnabled(true);
        txtEmail.setEnabled(true);
        cbxSituation.setEnabled(true);
        txtStreet.setEnabled(true);
        txtDistrict.setEnabled(true);
        txtComplement.setEnabled(true);
        txtNumber.setEnabled(true);
        txtCep.setEnabled(true);
        txtCity.setEnabled(true);
        cbxState.setEnabled(true);
    }
    
    private void disableText (){
        txtCpf.setEnabled(true);
        txtPhone.setEnabled(false);
        txtName.setEnabled(false);
        cbxSex.setEnabled(false);
        txtEmail.setEnabled(false);
        cbxSituation.setEnabled(false);
        txtStreet.setEnabled(false);
        txtDistrict.setEnabled(false);
        txtComplement.setEnabled(false);
        txtNumber.setEnabled(false);
        txtCep.setEnabled(false);
        txtCity.setEnabled(false);
        cbxState.setEnabled(false);
        btnSave.setEnabled(false);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegisterStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cbxSex;
    private javax.swing.JComboBox cbxSituation;
    private javax.swing.JComboBox<String> cbxState;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblComplement;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDistrict;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblRegisterStudents;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblSituation;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtComplement;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtDistrict;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JFormattedTextField txtPhone;
    private javax.swing.JTextField txtStreet;
    // End of variables declaration//GEN-END:variables
}
