/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author kaleo
 */
public class FormRegisterModality extends javax.swing.JFrame {

    /**
     * Creates new form FormRegisterModality
     */
    public FormRegisterModality() {
        initComponents();
        setLocationRelativeTo(null);//centralizar tela
        disableText();
        btnSave.setEnabled(false);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlModality = new javax.swing.JPanel();
        pnlButtons = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblNameModality = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPriceModality = new javax.swing.JLabel();
        txtPrice = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Academia King Muay Thai");
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlModality.setPreferredSize(new java.awt.Dimension(800, 600));

        pnlButtons.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Adicionar usuário masculino-104.png"))); // NOI18N
        btnCreate.setToolTipText("Adicionar novo Aluno");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCreate);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Salvar Filled-50.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSave);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Editar-104.png"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlButtons.add(btnUpdate);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Cancelar-104.png"))); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCancel);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Lixo-104.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlButtons.add(btnDelete);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-Pesquisa propriedade-50.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSearch);

        lblId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblId.setText("ID:");

        txtName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        lblNameModality.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNameModality.setText("Nome:");

        txtEmail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        lblPriceModality.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPriceModality.setText("Valor:");

        try {
            txtPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.00")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPrice.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlModalityLayout = new javax.swing.GroupLayout(pnlModality);
        pnlModality.setLayout(pnlModalityLayout);
        pnlModalityLayout.setHorizontalGroup(
            pnlModalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModalityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameModality, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlModalityLayout.createSequentialGroup()
                        .addComponent(lblPriceModality, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlModalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlModalityLayout.setVerticalGroup(
            pnlModalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModalityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModalityLayout.createSequentialGroup()
                        .addGroup(pnlModalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlModalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameModality, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlModalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPriceModality, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlModality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlModality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        flagButton=1;
        enabledText();
        btnSave.setEnabled(true);
        btnCancel.setEnabled(true);
        btnSearch.setEnabled(false);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (flagButton==1){
            personMod.setCpf(txtCpf.getText().replace(".","").replace("-",""));
            //personMod.setPhone(txtPhone.getText());
            personMod.setName(txtName.getText());
            personMod.setSex((String)cbxSex.getSelectedItem());
            //personMod.setEmail(txtEmail.getText());
            personMod.setStreet(txtStreet.getText());
            personMod.setDistrict(txtDistrict.getText());
            personMod.setNum(Integer.parseInt(txtNumber.getText()));
            personMod.setCep(txtCep.getText().replace("-",""));
            personMod.setCity(txtCity.getText());
            personMod.setState((String)cbxState.getSelectedItem());
            personMod.setComplement(txtComplement.getText());
            studentMod.setSituation((String)cbxSituation.getSelectedItem());
            studentCon.SaveStudent(personMod, studentMod);
            clearText();
            btnCancel.setEnabled(true);
            btnDelete.setEnabled(true);
            btnUpdate.setEnabled(true);
        }
        else {
            personMod.setCpf(txtCpf.getText().replace(".","").replace("-",""));
            //personMod.setPhone(txtPhone.getText());
            personMod.setName(txtName.getText());
            personMod.setSex((String)cbxSex.getSelectedItem());
            //personMod.setEmail(txtEmail.getText());
            personMod.setStreet(txtStreet.getText());
            personMod.setDistrict(txtDistrict.getText());
            personMod.setNum(Integer.parseInt(txtNumber.getText()));
            personMod.setCep(txtCep.getText().replace("-",""));
            personMod.setCity(txtCity.getText());
            personMod.setState((String)cbxState.getSelectedItem());
            personMod.setComplement(txtComplement.getText());
            studentMod.setCpf(txtCpf.getText().replace(".","").replace("-",""));
            studentMod.setSituation((String)cbxSituation.getSelectedItem());
            personCon.updatePerson(personMod);
            studentCon.updateStudent(studentMod);
            disableText();
            btnCreate.setEnabled(false);
            btnSave.setEnabled(false);
            btnCancel.setEnabled(true);
            btnDelete.setEnabled(true);
            btnUpdate.setEnabled(true);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        flagButton = 2;
        enabledText();
        btnSave.setEnabled(true);
        btnDelete.setEnabled(false);
        btnSearch.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearText();
        disableText();
        btnCreate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnSearch.setEnabled(true);

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int question = 0;
        question = JOptionPane.showConfirmDialog(rootPane, "Deseja relamente excluir os dados ?");
        if (question==JOptionPane.YES_OPTION){
            personMod.setCpf(txtCpf.getText().replace(".","").replace("-",""));
            studentCon.deleteStudent(personMod, studentMod);
            clearText();
            disableText();
            btnDelete.setEnabled(false);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        personMod.setSearch(txtCpf.getText());
        studentMod.setSearch(txtCpf.getText());
        PersonModel model = personCon.searchPerson(personMod);
        StudentModel stmodel = studentCon.searchStudent(studentMod);
        txtCpf.setText(model.getCpf());
        //personMod.setPhone(txtPhone.getText());
        txtName.setText(model.getName());
        cbxSex.setSelectedItem(model.getSex());
        //personMod.setEmail(txtEmail.getText());
        txtStreet.setText(model.getStreet());
        txtDistrict.setText(model.getDistrict());
        txtNumber.setText(Integer.toString(model.getNum()));
        txtCep.setText(model.getCep());
        txtCity.setText(model.getCity());
        cbxState.setSelectedItem(model.getState());
        txtComplement.setText(model.getComplement());
        cbxSituation.setSelectedItem(stmodel.getSituation());
        btnDelete.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnCreate.setEnabled(false);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void clearText (){
        txtCpf.setText("");
        txtName.setText("");
        //cbxSex.set("");
        txtEmail.setText("");
        //cbxSituation.set("");
        txtStreet.setText("");
        txtDistrict.setText("");
        txtComplement.setText("");
        txtNumber.setText("");
        txtCep.setText("");
        txtCity.setText("");
        //cbxState.setText("");
    }
    
    private void enabledText (){
        txtCpf.setEnabled(true);
        txtPhone.setEnabled(true);
        txtName.setEnabled(true);
        cbxSex.setEnabled(true);
        txtEmail.setEnabled(true);
        cbxSituation.setEnabled(true);
        txtStreet.setEnabled(true);
        txtDistrict.setEnabled(true);
        txtComplement.setEnabled(true);
        txtNumber.setEnabled(true);
        txtCep.setEnabled(true);
        txtCity.setEnabled(true);
        cbxState.setEnabled(true);
    }
    
    private void disableText (){
        txtCpf.setEnabled(true);
        txtPhone.setEnabled(false);
        txtName.setEnabled(false);
        cbxSex.setEnabled(false);
        txtEmail.setEnabled(false);
        cbxSituation.setEnabled(false);
        txtStreet.setEnabled(false);
        txtDistrict.setEnabled(false);
        txtComplement.setEnabled(false);
        txtNumber.setEnabled(false);
        txtCep.setEnabled(false);
        txtCity.setEnabled(false);
        cbxState.setEnabled(false);
        btnSave.setEnabled(false);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegisterModality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegisterModality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegisterModality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegisterModality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegisterModality().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNameModality;
    private javax.swing.JLabel lblPriceModality;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlModality;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JFormattedTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
